### PR TITLE
use values in closures instead of attaching properties to returned objects

### PR DESCRIPTION
**Pull request by airstruck**
Also add functions to access closure values that were previously attached to returned objects, and a little cleanup

### CODE REVIEW

**Comment by tesselode** [comment]
Actually, I just thought of something. If you call the detectors' getValue function from buttons and axes, that means that if there's more than one button or axis using the same detector, that function gets called more than once, which is a little inefficient. So now I'm not sure which is the best way to go.

**Comment by airstruck** [comment]
I thought about that too, but I figured you'd never have enough buttons/axes rigged up to a single detector to notice the difference. I might not be thinking about the same kind of use cases you're thinking of, though. Can you think of an example where you'd have more than, say, 2 buttons hooked up to one detector?

Another thing you could do to boost efficiency a little is break from `axis.update()` and `button.update()` as soon as you find a non-zero value, so it would take the first value it finds instead of the last.

I'll take another look at this when you get the test thing set up, I'm looking around for a USB gamepad now :)

**Comment by tesselode** [comment]
Yeah, efficiency shouldn't be a big deal. I can't think of any use cases where your way would slow things down noticeably, but _technically_ it's less efficient. Either way, using variables seems more intuitive to me, but it's really just a matter of personal preference. I'm still debating!

Also, the test should be up, so have fun with that. :P

**Comment by airstruck** [comment]
- Removed most `update()` functions, it's only really needed for checking when buttons are pressed/released in this fork. I'd like to remove `tactile.update()` entirely if there's a reasonable way to do it.
- Made a few things locals instead of members of tactile, saw no reason to expose them publicly.
- Functions that took a table of detectors now take detectors as varargs, so you can write
  
  ```
  input.addAxis(keyboardXAxis, gamepadXAxis)
  ```
  
  instead of
  
  ```
  input.addAxis({ keyboardXAxis, gamepadXAxis })
  ```
- Got rid of `removeByValue()`; storing the object as the key instead of the value, so they can be removed like `t[object] = nil`
- Removed some other internal things that were no longer needed in this fork

Not tested with gamepad (still haven't found mine).

**Comment by airstruck** [comment]
Still streamlining things... under this fork, there's no reason for detectors to be objects since they only exposed one method. All detectors are now functions that take no arguments and return a single numeric value.

Considered using love events to help detect pressed/released things and getting rid of `tactile.update()`, but it wouldn't work for "axis buttons." Still thinking about ways to get rid of update though.

tactile.lua is down from about 300 lines of code to about 200.

**Comment by tesselode** [comment]
I've been asking around and getting some advice, and for now, I'm going to keep the update functions for a couple of reasons.
1. I need an update function anyway for buttons, so I may as well update everything else while I'm at it.
2. It's good that the detectors and controls update once per frame so that they can't change values in the middle of a frame.

You should keep doing stuff, though! The changes you're making are really interesting, and if I don't end up merging your changes, you can just make your own library based on mine. It seems like it's going in a different direction, anyway. I'm curious to see what you can do with it.

**Comment by tesselode** [comment]
Also, if I delete the dev branch in my repo, will that break anything horribly?

Edit: nvm, I got things figured out. No deleting branches for me!

**Comment by airstruck** [comment]
> It's good that the detectors and controls update once per frame so that they can't change values in the middle of a frame.

Hmm, didn't think about that. Not sure why you'd need to check a control more than once per frame though, but if you did want to for some reason, wouldn't you want the most up-to-date value?

Now I can see where if you had multiple controls using the same detector, the detector could return two different values within a frame, and that _might_ cause problems, although I can't really think of a concrete example of a problem it would cause, and I can't think of a realistic case where you'd want multiple controls hooked up to the same detector anyway.

Also not familiar enough with Love internals to know whether it's actually possible to get different values during a single frame. For all I know it can't actually happen...

If you want we can just close this PR, could make a mess now that I've merged your newer changes in. I've seen that get hairy before.

I may just go in a different direction with mine, because many of the addFoo functions don't have names reflecting what they actually do anymore, since they just return a "foo" rather than adding it to anything (and there's no longer anything to remove them from either, you just stop using them when you're done with them).

**Comment by tesselode** [comment]
Now that I think about it, you probably can't get different inputs in the same frame. The input stuff and love.update are both in the same main loop, so it should be OK.

And yeah, I'll go ahead and close this, it _is_ starting to get kind of nasty.

**Pull request closed without merging**
