### PR TITLE
Some API changes

### PR DESCRIPTION
**Pull request by ghost**
- Added the ability for some detector creators to accept multiple keys/buttons
- Added a few more detectors
- Changed argument ordering of gamepad functions to accept gamepad number first, to accommodate multiple buttons
- Pluralized some function names
- Allowed gamepad detector functions to accept either Joystick objects or numbers
- Made some changes to error handling

Pick and choose any of the changes you do or don't like. :+1:

### CODE REVIEW

**Comment by tesselode** [comment]
These are really nice changes :O I'll get to work on reviewing some of these commits within the next couple of days. What situation do you imagine boolean axis detectors will be useful in? I want to avoid adding detectors that are barely going to be used, as I feel like it would make the API harder to learn/remember for little benefit.

**Comment by ghost** [comment]
Thanks, and that's a good question about the boolean axis. The `triggerleft` and `triggerright` pan between 0 and 1, and not -1 and 1. Where the binaryAxis emulates the behavior of the left and right stick axes for gamepads, the boolean axis is to do the same for triggers. Especially for driving games, for example, where the triggers are used for variable acceleration/breaking.

It was mostly an idea I just threw in for the sake of it as I'd just come up with it, and the implementation (and probably naming as well) can be improved a bit. It could just give 0 and 1 depending on a button axis detector state, but I wanted to provide the ability to define both values for the sake of flexibility. If a situation that complicated comes up, though, they can probably just make their own detector for that.

**Comment by tesselode** [comment]
That could actually be pretty useful. It makes me wonder, could there be an axis detector that's a more general form of binary/boolean axis detectors? Maybe something where you can plug in any number of button detectors and assign them each an amount, and the axis value is the sum of the button detectors that are currently triggered? That would reduce the number of functions in the API, although maybe at the cost of intuitiveness (although right now I don't think either the binary axis detector or the threshold button detector is very intuitive).

**Comment by tesselode** [comment]
OR: what if the binary axis detector gave you the option to only map positive or negative, making it 0-1 or -1-0?

**Comment by ghost** [comment]
The naming of things is a part of it. It's possible you could rename the boolean/binary axis detectors to "buttonAxis" or something along those lines, if such a function were available.

Another idea, however, is to combine all the things into a single input object that can have an `isDown` state, _and_ an axis value. It's considered down when the axis value goes beyond the deadzone.

I'll add that usability definitely comes first, though. Gotta make sure that someone who's only been using LOVE for no more than a week or two can use the API. Flexibility is already accounted for with the awesome idea of just using functions for detectors.

> OR: what if the binary axis detector gave you the option to only map positive or negative, making it 0-1 or -1-0?

That'd work. I'm guessing in this case, you could either leave one of the arguments nil, or just give a range for the binary axis to work with. But I can't see a lot of cases where someone would logically need a range of -1 to 0, when 0 to 1 will almost always do the same thing, just by flipping the number.

**Comment by tesselode** [comment]
> Another idea, however, is to combine all the things into a single input object that can have an isDown state, and an axis value. It's considered down when the axis value goes beyond the deadzone.

I actually really like that idea. The detectors that convert between axes and buttons are kind of hard to think about, and this would solve that issue. Hopefully combining the two isn't too unintuitive. I'll try playing around with it tomorrow. Do you think something like that would be Tactile 2.0 or a separate library entirely?

**Comment by ghost** [comment]
I don't think it would be _too_ unintuitive, though.  For buttons, value would either be 0 or 1, `:isDown()` would be `math.abs(value) > deadzone`, and `:pressed()` and `:released()` logic all work the same.

Depending on how much the user API changes, maybe 2.0. If the API functions remain mostly the same, a bump to 1.3 is probably fine enough.

**Comment by tesselode** [comment]
What do you think of the changes on the rewrite branch so far?

**Comment by ghost** [comment]
Looks pretty great! There seems to be a lot of conditional noise, though, with `if`s, `then`s, `else`s and junk. Could probably stand to squish a few. e.g.

``` lua
function Control:addPositiveButtonDetector(f)
  table.insert(self._detectors, function()
    return f() and 1 or 0
  end)
end
```

``` lua
function Control:addButtonPair(negative, positive)
  table.insert(self._detectors, function()
    local n, p = negative(), positive()
    return n and p and 0
    or n and -1
    or p and 1
    or 0
  end)
end
```

``` lua
function Control:isDown(dir) -- probably error here if dir is not a number, instead of checking in conditional
  local value = self:getValue()
  return value ~= 0 and dir and sign(value) == sign(dir)
end
```

**Comment by tesselode** [comment]
Can you make a pull request for those? I could just add it myself, but then it looks like I'm doing everything. I want the different contributors to show up so it can look like a fun happy community thing. :P

However, don't add the changes to `Control:isDown`. I think you actually changed the meaning of the function; `dir` is supposed to be optional. If you don't specify a direction, it'll check whether the control is down in either direction.

**Comment by ghost** [comment]
Sure thing, I'll get on that in a bit.

And I see what you mean with isDown. So:
- If `dir` is specified, check if the sign of `dir` is the sign of `value`.
- If `dir` is nil, check if value is not 0.

``` lua
function Control:isDown(dir)
  local value = self:getValue()
  return dir and sign(value) == sign(dir) or value ~= 0
end
```

Should work. Turning it into a simple ternary based off of dir's truthy value made it look a little more straightforward and nice. Thanks for pointing that out.

And it also makes me think that, despite being concise and flexible, there's not really a good way to explain that clearly. I'm thinking it'd be clearer to split it up into `:isNegativeDown()` and `:isPositiveDown()`, where `:isDown()` would return true if either are down. Or possibly, just have a function `:isAxisDown()` that accepts the number and checks it then.

Overall, the more optional arguments a function has, the more complexity is added, and the more explanation is required for it, so maybe that should be avoided as a whole?

**Comment by tesselode** [comment]
Writing `Control:isDown` that way still wouldn't work, as `sign(x)` returns 1 if `x` >= 0. So if `dir` == 0 and `value` == 0, `isDown` will return `true`, which is a false positive. Maybe I should change `sign` to return 0 if `x` == 0, but for now I just had it written like sign functions are usually written. Actually, yeah, that would be a good idea.

As for having separate `isDown` functions for negative, positive, and neutral, I think that will become very bloaty as you'll also have to write separate functions for `pressed` and `released`. Now we have 9 functions, which is complicated in its own way. I see what you mean though; the meaning of `isDown(-1)` wouldn't be obvious just from reading it.

**Comment by ghost** [comment]
> Maybe I should change sign to return 0 if x == 0, but for now I just had it written like sign functions are usually written. Actually, yeah, that would be a good idea.

... You should definitely do that. Mathematically, 0 doesn't have a sign. :P 

> As for having separate isDown functions for negative, positive, and neutral, I think that will become very bloaty as you'll also have to write separate functions for pressed and released. Now we have 9 functions, which is complicated in its own way. I see what you mean though; the meaning of isDown(-1) wouldn't be obvious just from reading it.

Good point, I didn't think about the pressed/released functions. I have a solution in mind, but I'll need to do some more testing with it to see if it's logically sound, because it goes even further down my massive rabbit hole of abstraction:

Only represent controls as values from 0 to 1, and take negatives out of the equation entirely. While making things simpler to reason about and document, it does add the limitation of not being able to use bidirectional axes. However, a bidirectional axis can still be represented by two axes in this system, with the left being flipped/subtracted by the user.

**Comment by tesselode** [comment]
> Only represent controls as values from 0 to 1, and take negatives out of the equation entirely. While making things simpler to reason about and document, it does add the limitation of not being able to use bidirectional axes. However, a bidirectional axis can still be represented by two axes in this system, with the left being flipped/subtracted by the user.

...That sounds like an incredible pain. :P

**Comment by ghost** [comment]
It does, but it's actually not that difficult:

``` lua
moveLeft = tactile.newControl(tactile.keys('left'), ...)
moveRight = tactile.newControl(tactile.keys('right'), ...)

-- later, assuming :move changes x and y position
player:move(player.speed * dt * (moveRight:getValue() - moveLeft:getValue()), 0)
```

Where even the common "if moveRight/moveLeft:isDown()" statements would probably be fine compared to the usual method of handling input. A sacrifice of verbosity for more logical solidity?

Optionally, there could just be a wrapper that accepts two 0-1 controls and flips the second one for you, therefore working as a binary axis value, but you'd access the positive and negative sides and check `:isDown()` on either of them yourself. Something like this?

``` lua
movement = tactile.newBinaryControl(moveLeft, moveRight)

player:move(player.speed * dt * movement:getValue())

if movement.positive:isDown() then
  -- stuff
end
```

A somewhat awkward way of doing it, but I'm totally in favor of tossing negatives out the window.

**Comment by tesselode** [comment]
From a button perspective, your way is more logical, but from an axis perspective it's pretty suboptimal. I think the case where buttons are used to operate an axis is more common than the other way around, so I'm biased towards whatever makes axes the most full-featured.

**Comment by ghost** [comment]
In that case, optionally checking directions with `:isDown()` and `:pressed()` seems to be the best way of going about it while still keeping bidirectional axes, even if it doesn't read well.

**Comment by tesselode** [comment]
It's the best I can think of. Alternatively, you could pass in a string argument (`'negative'` or `'positive'`), but that's gross.

**Comment by ghost** [comment]
That's super gross. :-1: 

But yeah. I don't really know if there's any non-complicated way to have both bidirectional axes and button logic shoehorned in one thing, except while just having unidirectional axes. Could just backtrack to the original way tactile worked, but having button detectors that can still report 0-1 values as though they were axes.

**Comment by ghost** [comment]
Wait. isDown, pressed, and released can all just return numbers. There's probably a problem with this but I have yet to see one.

``` lua
-- common case works
if control:pressed() then

-- complicated case works
if control:pressed() == -1 then
```

And, of course, they'd return false or nil if not pressed/released/down.

**Comment by tesselode** [comment]
Even with the weird `dir` argument, I still think this idea is worth pursuing. I'm pretty sure it'll result in much shorter code for common use cases than the old version; I'll come up with a demo soon.

> Wait. isDown, pressed, and released can all just return numbers. There's probably a problem with this but I have yet to see one.

I think this comes out to the same thing overall.

**Comment by ghost** [comment]
Eh, I dunno. Semantically it just seems nicer, and it reduces the code in the function to just `return sign(self:getValue())`, along with avoiding the optional, somewhat ambiguous argument, while still providing a truthy/falsy for common use. It's probably the best way to go here.

EDIT: No, that's not right, I'm stupid, lol. But still, no optional arg.

**Comment by ghost** [comment]
In fact, I don't really see the need for the boolean functions to even account for axes at all. If you need to check if a detector is in a specific direction, `:getValue() > 0` should be good enough, right?

**Comment by tesselode** [comment]
Perhaps? The main use case for the `dir` argument is mapping an axis to a button. For example, if you were using an analog stick to operate a menu, it would look something like this:

``` lua
if vertical:pressed(-1) then
  -- move cursor down
end
if vertical:pressed(1) then
  -- move cursor up
end
```

Without the `dir` argument, it would be something like this...

``` lua
if vertical:pressed() then
  if vertical:getValue() < 0 then
    -- move cursor down
  end
  if vertical:getValue() > 0 then
   -- move cursor up
  end
end
```

...which is a good amount more verbose. I think that would be kind of annoying to type out, and it's not super intuitive to read, either.

**Comment by ghost** [comment]
That's fair. I still think it's better given as a return result and not an argument, though.

**Comment by tesselode** [comment]
How come?

``` lua
if vertical:pressed(-1) then
  -- move cursor up
end
```

``` lua
if vertical:pressed() == -1 then
  -- move cursor up
end
```

They feel about the same to me.

**Comment by ghost** [comment]
Because of the ambiguous argument, and they can also check if it's less than or equal to 0.

**Comment by tesselode** [comment]
When would it ever be equal to 0?

**Comment by ghost** [comment]
I meant greater than, sorry.

**Comment by tesselode** [comment]
Well, I'm going to leave it for now. It feels weird if `pressed` and `released` return something other than boolean; it's especially weird if they can be any number. Can you think of anything that needs implementing? I'm sure I'm forgetting plenty of things. A unit test, for one...

**Comment by ghost** [comment]
I can't, no. And I guess it'll be fine the way it is. You should go ahead and make any needed changes before I clean stuff up, if anything needs to be done.

**Comment by tesselode** [comment]
Go ahead and start. Merge conflicts shouldn't be too hard to resolve anyway.

**Comment by ghost** [comment]
Alright, pretty much did all I wanted to do.

**Comment by tesselode** [comment]
Could you throw in that error handling you had previously? Would that translate easily to the new API? Also, your changes are a little out of date, I did some stuff yesterday.

**Comment by ghost** [comment]
I figured. :U 

But here's the error handling. Like before, I only implemented it in the API interface, since that should be what the user's going to be working with 90% of the time.

**Comment by shakesoda** [comment]
Is there an actual use case for scancodes in tactile?

**Comment by ghost** [comment]
That's a good question. The only reason I threw it in is because it exists. I have yet to see anyone actually use them.

**Comment by tesselode** [comment]
@Kingdaro, I cherry-picked your two most recent commits into the rewrite branch.

**Comment by ghost** [comment]
:+1:

**Comment by pevzi** [comment]
I like the new API. Here are my two (three?) cents.
- I'd suggest to move all the calculations from `getValue` to `update` and make `getValue` just return `_currentValue` so that the calculations are performed only once a frame.
- I'm a bit concerned about performance of using `unpack` in detectors even in cases when there is only one key to check. Probably not a big deal though?
- The `any` function declared at the top of the module seems to not be used anywhere.

**Comment by ghost** [comment]
> I'm a bit concerned about performance of using unpack in detectors even in cases when there is only one key to check. Probably not a big deal though?

There's no faster, more concise way to do it because of how functions and variable arguments work in Lua.

**Comment by tesselode** [comment]
> I'd suggest to move all the calculations from getValue to update and make getValue just return _currentValue so that the calculations are performed only once a frame.

I could do that, but what about a theoretical case where somebody doesn't need to use `pressed` or `released`? Then they could skip calling `update`. Will that ever happen? I don't know, probably not.

> I'm a bit concerned about performance of using unpack in detectors even in cases when there is only one key to check. Probably not a big deal though?

How important is performance in a case like this? Performance is always good to look out for, but I have a hard time seeing how a library like this could significantly impact performance.

> The any function declared at the top of the module seems to not be used anywhere.

You're absolutely right; I was using that earlier but not anymore. I am a silly.

**Comment by pevzi** [comment]
> I could do that, but what about a theoretical case where somebody doesn't need to use pressed or released? Then they could skip calling update.

Well, then it is kinda confusing that some of the use cases require calling `update` and some do not. Especially since you've generalized the API for both axes and "regular" buttons.

**Comment by tesselode** [comment]
What do axes have to do with anything? They don't use `update`. Regardless, you're probably right, I'm not going to say, "well you don't _have_ to use `update`," that'll just be confusing. I may as well assume people will use it.

**Comment by pevzi** [comment]
> What do axes have to do with anything? They don't use update.

I mean, old Axes didn't have an `update` method at all so there was no choice as to use it or not. But now it's a single Control class that has `update` regardless of whether it is used for buttons or axes. Just a matter of consistency I think.

It's probably worth listening to someone else's opinion then.

**Comment by tesselode** [comment]
I hear you, consistency is good. I'll probably go ahead and have `getValue` use the variables.

**Comment by pevzi** [comment]
I think you forgot to add `Control:update`s to the example in README.

**Comment by tesselode** [comment]
Fixed, thanks!

**Comment by tesselode** [comment]
Everything I liked from this pull request has been worked into the new version of Tactile. Man, this really spiraled out of control, huh?

**Pull request closed without merging**
